
name: releasenote

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Check for release note
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_api_url: 'api.github.com' # It would be ideal to test this out pointing to a GitHub Enterprise server, but there are no testing environments available